### ISSUE TITLE
GoogleAnalytics Undefined Symbols

### ISSUE THREAD

**Issue by bassrock** [CocoaPods/swift#16]
I am using google analytics and keep getting an undefined symbols for architectures when I try to build and run an iOS app. To verify this was indeed a Google Analytics error I created a single view test application with just the google analytics pod and tried to use a GAITrackedViewCOntroller. It then received the same error:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_GAITrackedViewController", referenced from:
      _OBJC_CLASS_$_ViewController in ViewController.o
  "_OBJC_METACLASS_$_GAITrackedViewController", referenced from:
      _OBJC_METACLASS_$_ViewController in ViewController.o
ld: symbol(s) not found for architecture x86_64
```

Are there any work arounds for this or is this a Google issue?

**Comment by neonichu** [comment]
Closing this in favour of CocoaPods/CocoaPods#3106 which includes the actual cause of this.
