### ISSUE TITLE
Could not build Objective-C module

### ISSUE THREAD

**Issue by pepibumur** [CocoaPods/swift#17]
After integrating the Swift library with an empty project I get that error compiling the project. Am I doing something wrong?
![image](http://cl.ly/image/2n0s303w2e1u/Image%202014-12-25%20at%203.34.15%20pm.png)

**Comment by ashfurrow** [comment]
Experiencing a similar issue. @mrackwitz can you clarify the header public/private difference?

**Comment by mrackwitz** [comment]
Public Headers are compiled with the framework and with the application target, so everything which is included there has to fulfill the requirements for Clang Modules. Foreign code from other dependencies must be importable as modules, which doesn't imply `@import/import`, but that there is a Clang module declaration. Private headers are only taken into account while compiling the framework itself.

**Comment by MaddTheSane** [comment]
IIRC, Frameworks need to have a module definition file defined. If it doesn't it can be imported into Swift via the bridging header.

**Comment by neonichu** [comment]
It is actually the other around. If you do have a module, the bridging header is not necessary and you can import the framework directly, otherwise you need to use the bridging header.

**Comment by ashfurrow** [comment]
@pepibumur In my case, rebuilding the entire Xcode project from scratch and re-integrating with CocoaPods fixed this for me (see [this](https://github.com/artsy/eidolon/commit/95be833caa5e2babe25f7ceec8b1c7ee04deb6fa) commit on [this](https://github.com/artsy/eidolon/pull/351) PR). My hypothesis is that a previous pre-release version of CocoaPods w/ frameworks set some flag or something in my project and later, with 0.36 Beta 1, it is now incompatible.

**Comment by pepibumur** [comment]
Hello @ashfurrow thanks for the report. Tried it with the beta 1 but now I get this error
![image](http://cl.ly/image/1R0V260v1q3k/Image%202015-01-10%20at%2012.51.22%20am.png).

**Comment by pepibumur** [comment]
Ups sorry!, didn't install the beta 1 properly. It's working now :stuck_out_tongue: . Great job guys, and thanks @ashfurrow

**Comment by inetfuture** [comment]
@mrackwitz @pepibumur I'm trying to distribute a objective-c static library as a framework, and facing the same error, could you please take a look and tell me what am I doing wrong? I have stuck on this all day.

Here is the podspec https://github.com/tuisongbao/realtime-engine-client-ios/blob/master/TuisongbaoRealtimeEngine.podspec and framework https://github.com/tuisongbao/realtime-engine-client-ios/tree/master/TuisongbaoRealtimeEngine.framework

I noticed one strange behavior: if I add bridging header, it works, and if I then delete the bridging header, it still works, but not before I added the bridging header. I used git to track the difference before and after the bridging header was added:

``` diff
--- a/t2.xcodeproj/project.pbxproj
+++ b/t2.xcodeproj/project.pbxproj
@@ -323,10 +323,13 @@
            baseConfigurationReference = 414C49CFDB79090E45B86F89 /* Pods-t2.debug.xcconfig */;
            buildSettings = {
                ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
+               CLANG_ENABLE_MODULES = NO;
                INFOPLIST_FILE = t2/Info.plist;
                LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
                PRODUCT_BUNDLE_IDENTIFIER = com.inetfuture.t2;
                PRODUCT_NAME = "$(TARGET_NAME)";
+               SWIFT_OBJC_BRIDGING_HEADER = "";
+               SWIFT_OPTIMIZATION_LEVEL = "-Onone";
            };
            name = Debug;
        };
@@ -335,10 +338,12 @@
            baseConfigurationReference = C18DF9E997AB08EAE4B13E76 /* Pods-t2.release.xcconfig */;
            buildSettings = {
                ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
+               CLANG_ENABLE_MODULES = NO;
                INFOPLIST_FILE = t2/Info.plist;
                LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
                PRODUCT_BUNDLE_IDENTIFIER = com.inetfuture.t2;
                PRODUCT_NAME = "$(TARGET_NAME)";
+               SWIFT_OBJC_BRIDGING_HEADER = "";
            };
            name = Release;
        };
```

So I tried to add the `CLANG_ENABLE_MODULES` option to podspec, no lucky.

Although adding bridging header will make it work, but I'm trying to omit this step to make my users' life easier. Am I doing something wrong, or is it not possible(a bridging header must be used)?

Thanks.
