### ISSUE TITLE
dyld: Library not loaded: @rpath/libswiftCore.dylib

### ISSUE THREAD

**Issue by jhersh** [CocoaPods/swift#19]
I'm not entirely sure this is a CocoaPods issue. If it isn't, please feel free to close.

I have a [pure Swift project](https://github.com/splinesoft/bequest) with a mix of Swift and Obj-C pods. Podfile [is here](https://github.com/splinesoft/Bequest/blob/master/src/Podfile). The app runs just fine in the simulator with the debugger attached, but launching the app in simulator without the debugger, and any attempt to run on a real device, crash immediately:

```
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /private/var/mobile/Containers/Bundle/Application/82F6A5BF-D2C5-4F61-A15F-EBF8AE1B9974/Bequest.app/Bequest
  Reason: no suitable image found.  Did find:
	/private/var/mobile/Containers/Bundle/Application/82F6A5BF-D2C5-4F61-A15F-EBF8AE1B9974/Bequest.app/Frameworks/libswiftCore.dylib: code signature invalid for '/private/var/mobile/Containers/Bundle/Application/82F6A5BF-D2C5-4F61-A15F-EBF8AE1B9974/Bequest.app/Frameworks/libswiftCore.dylib'

	/private/var/mobile/Containers/Bundle/Application/82F6A5BF-D2C5-4F61-A15F-EBF8AE1B9974/Bequest.app/Frameworks/libswiftCore.dylib: code signature invalid for '/private/var/mobile/Containers/Bundle/Application/82F6A5BF-D2C5-4F61-A15F-EBF8AE1B9974/Bequest.app/Frameworks/libswiftCore.dylib'
```

[This question](http://stackoverflow.com/questions/24002836/dyld-library-not-loaded-rpath-libswift-stdlib-core-dylib) seems not entirely dissimilar and so far I've tried:

- verifying my runpath search paths are correct: `@executable_path/Frameworks` and `@loader_path/Frameworks`
- Set `EMBEDDED_CONTENT_CONTAINS_SWIFT` to `YES` on the application target and all Pods targets
- Added `Pods_Bequest.framework` as an Embedded Binary on the project's General tab in Xcode
- Creating a new debug provisioning profile for the app. The SO page also suggests regenerating your certs; I've not done so yet

Also activating the @segiddins signal!

**Comment by segiddins** [comment]
The swift runtime dylibs must not be signed. If no one beats me to it, I can take a look at the embed frameworks script.

**Comment by oveddan** [comment]
This happens to me too

**Comment by fitch** [comment]
Happens to me too. Tried setting `EMBEDDED_CONTENT_CONTAINS_SWIFT` to `YES` on the application target, and it worked for a while. Now it doesn't anymore.

**Comment by hajile** [comment]
@segiddins Actually, 

changing
```
  for lib in $swift_runtime_libs; do
    echo "rsync -av \"${SWIFT_STDLIB_PATH}/${lib}\" \"${destination}\""
    rsync -av "${SWIFT_STDLIB_PATH}/${lib}" "${destination}"
  done
```

to

```
  for lib in $swift_runtime_libs; do
    echo "rsync -av \"${SWIFT_STDLIB_PATH}/${lib}\" \"${destination}\""
    rsync -av "${SWIFT_STDLIB_PATH}/${lib}" "${destination}"
    if [ "${CODE_SIGNING_REQUIRED}" == "YES" ]; then
      code_sign "${destination}/${lib}"
    fi
  done
```

in `Pods-***-frameworks.sh` fixes the issue

**Comment by segiddins** [comment]
@hajile that change is tracked by https://github.com/CocoaPods/CocoaPods/pull/3009

**Comment by mrackwitz** [comment]
@jhersh: Can you confirm that this solves the problem also for you? Then we can close this issue.

**Comment by jhersh** [comment]
@mrackwitz thanks again for all your work on this, by the way!

I modified my frameworks script as per @hajile's comment above. Running on the device I now see a slightly different error on launch:

```
dyld: Library not loaded: @rpath/Pods_Bequest.framework/Pods_Bequest
  Referenced from: /private/var/mobile/Containers/Bundle/Application/A4E74EA4-F587-4CD7-868B-3F2F3F5A43FA/Bequest.app/Bequest
  Reason: image not found
```

I added `Pods_Bequest.framework` as an Embedded Binary on my project's General tab and that seems to have resolved it - for the first time, I'm able to run my app on my device!

**Comment by mrackwitz** [comment]
@jhersh: Could you make sure that in your project there is a `Embed Pods Frameworks` build phase? This is supposed to do automatically (with some advanced logic Xcode doesn't support), what you now did manually. Otherwise you could delete the `Pods.framework` from your `Link Binary with Libraries` list and run `pod install` again, so that the project integration will happen again and the described build phase will be (re-)added to your project.

**Comment by jhersh** [comment]
Yup, I do have that build phase. I deleted the pods framework and ran `pod install` again but it's back to `dyld: Library not loaded: @rpath/Pods_Bequest.framework/Pods_Bequest`. If you like you can see [my project](https://github.com/splinesoft/bequest).

**Comment by fitch** [comment]
Making the changes suggested by @hajile to `Pods-xxx-frameworks.sh` worked for me.

**Comment by segiddins** [comment]
Those changes have been merged at https://github.com/CocoaPods/CocoaPods/pull/3009.

**Comment by mojtabacazi** [comment]
Just got this:

``````
dyld: Library not loaded: @rpath/Pods.framework/Pods
  Referenced from: /private/var/mobile/Containers/Bundle/Application/96974BD8-2E16-42D2-8352-6528C743B5B3/water-dev.app/project-dev
  Reason: image not found```
``````

**Comment by mojtabacazi** [comment]
Solution 

http://stackoverflow.com/questions/29126835/swift-framework-depending-on-cocoa-pod

**Comment by thiagoramos23** [comment]
The solution added by @ilya-epifanov worked for me. Thanks.

**Comment by anismansuri63** [comment]
just clean the project
shift+cmd+k

**Comment by nobody4t** [comment]
I got this too. This time I got no luck to resolve this with any answer. The Apple is really a myth. At least for me.
