### ISSUE TITLE
TARGET_BUILD_DIR wrong for Archive builds

### ISSUE THREAD

**Issue by fluidsonic** [CocoaPods/swift#20]
Different app targets can have the same Pod dependency which is fine since the Pod targets will have a different name. But during Archive builds one Pod target can overwrite another one's product since they use a shared folder for their products.

This leads to random errors during Archive builds like missing headers, codesign errors or that an Objective-C module couldn't be built.

[`TARGET_BUILD_DIR`](https://developer.apple.com/library/ios/documentation/DeveloperTools/Reference/XcodeBuildSettingRef/1-Build_Setting_Reference/build_setting_ref.html#//apple_ref/doc/uid/TP40003931-CH3-SW88) equals `CONFIGURATION_BUILD_DIR` when doing a normal build.
But for Archive builds `DEPLOYMENT_LOCATION` is set to `YES` so `TARGET_BUILD_DIR` changes and all target's products are thrown into the same directory: `DerivedData/PROJECT/Build/Intermediates/ArchiveIntermediates/TARGET/IntermediateBuildFilesPath/UninstalledProducts`.

CocoaPods should take care that each target has a different build directory (`TARGET_BUILD_DIR`) even when archiving.

**Comment by fluidsonic** [comment]
Looks like the documentation is wrong about `TARGET_BUILD_DIR`. It does not depend on `TARGET_TEMP_DIR` but on `TEMP_ROOT`.

But anyway I don't think it's possible to override the paths used for Archive builds.

Will check if a shell script can solve the issue.
This is really annoying. Most of our Archive builds suddenly fail because of this mess.

**Comment by fluidsonic** [comment]
We worked around the issue by not having the same pod multiple times in the same build process.

**Comment by neonichu** [comment]
This should be fixed by the deduplication described in CocoaPods/CocoaPods#3095
