### ISSUE TITLE
Dynamic framework issues with CocoaPods and Swift

### ISSUE THREAD

**Issue by getaaron** [CocoaPods/swift#22]
Is this correct?

- All pods written in Swift will be built as dynamic frameworks
- Dynamic frameworks only run on iOS 8 or later (iTunes Connect will reject apps if built for iOS 7)
- Therefore, if authors of a project written in Swift want to provide iOS 7 support, they should instruct developers of iOS 7 apps to install these projects manually, not using CocoaPods

If this is correct, I have two suggestions:

1. When running `pod spec lint`, this message:
      > NOTE  |  ld: warning: embedded dylibs/frameworks only run on iOS 8 or later.

  should more clearly indicate the consequences

2. https://github.com/CocoaPods/blog.cocoapods.org/pull/59 should be updated to explicitly include this information, since it's a significant limitation.

**Comment by kylef** [comment]
Yes this is correct (summarised this on https://github.com/Alamofire/Alamofire/pull/287#discussion_r22532091).

This will be an actually lint error by the 0.36 release. Enforcing that Swift pod's platform is set correctly (see https://github.com/CocoaPods/CocoaPods/issues/2963).

I think it make's sense to put this in the blog post. /cc @mrackwitz Perhaps this should also make it into the guides by the release of CocoaPods 0.36.

**Comment by ValCapri** [comment]
Is there no way to provide a static framework with Swift and iOS 7+ support? Like iOS-Universal-Framework project.
For the moment, I use CocoaPods for Objective-C dependency (so it produce static library) and submodules for swift dependency.

**Comment by mrackwitz** [comment]
@getaaron: As @kylef states, this will be an error, which will cause rejection of the podspec. I don't think this has to be necessarily stated into the blog post, as this is a general limitation of the OS / distribution platform and not the dependency manager.

@kylef: :+1:

@ValCapri: No, static frameworks are unlinked. Swift has to be linked because of it's dynamic standard libraries.

**Comment by getaaron** [comment]
@mrackwitz I think it's worth including in the blog post even though it's not a CocoaPods limitation, mostly because I suspect it will catch many people by surprise.

**Comment by AvdLee** [comment]
Conclusion here, Cocoapods with swift support will only work on iOS 8+?

I'm thinking to start using the latest Cocoapods with Swift support for my project, where I'm supporting iOS 7+.

**Comment by neonichu** [comment]
@AvdLee this is correct, Swift on iOS 7 only works if you copy the files into your application project.

**Comment by neonichu** [comment]
I drafted a little paragraph that could be part of the eventual 0.36 release blog post: <https://gist.github.com/neonichu/acd533ab9fcce4cf3a1b> - this should avoid unnecessary discussions on whether this is a CP limitation or whether it is temporary or not, as we can already see that for some reasons people are debating this.

**Comment by getaaron** [comment]
https://gist.github.com/getaaron/73a3a5eb776613681389 has some minor formatting and copy suggestions. (I also noted this in @neonichu's gist.)

**Comment by mrackwitz** [comment]
Done with https://github.com/CocoaPods/blog.cocoapods.org/commit/6933ae5ccfc1e0b39dd23f4ec67d7a083975836d.
