### ISSUE TITLE
Difference between trunk.cocoapods.org podspec validation and 0.36.0.beta.1 validation causes unreported push failure

### ISSUE THREAD

**Issue by mattt** [CocoaPods/swift#24]
I'm attempting to publish the Alamofire podspec (1.1.3) to the CocoaPods trunk.

When I do `$ pod --version`, I get:

```
0.36.0.beta.1
```

I am using Xcode Version 6.1.1 (6A2006).

### Podfile

```ruby
Pod::Spec.new do |s|
  s.name = 'Alamofire'
  s.version = '1.1.3'
  s.license = 'MIT'
  s.summary = 'Elegant HTTP Networking in Swift'
  s.homepage = 'https://github.com/Alamofire/Alamofire'
  s.social_media_url = 'http://twitter.com/mattt'
  s.authors = { 'Mattt Thompson' => 'm@mattt.me' }
  s.source = { :git => 'https://github.com/Alamofire/Alamofire.git', :tag => s.version }

  s.ios.deployment_target = '8.0'
  s.osx.deployment_target = '10.10'

  s.source_files = 'Source/*.swift'
end
```

When I do `$ pod trunk push Alamofire.podspec`, I get the following output:

```
Validating podspec
[!] Unable to load a specification for the plugin `/usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-try-release-fix-0.1.2`
[!] Unable to load a specification for the plugin `/usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-try-release-fix-0.1.2`
 -> Alamofire (1.1.3)
    - ERROR | [OSX]  Alamofire/Source/Alamofire.swift:1264:76: error: function produces expected type 'String?'; did you mean to call it with '()'?

[!] The podspec does not validate.
```

There are three things to call out here:

1. I don't know why the "Unable to load a specification for the plugin" warning is printing. Is this a known issue with this CocoaPods beta release?
2. I cannot reproduce the OS X error when building for the OS X framework target using a deployment target of OS X 10.10. I'm not sure what part of that statement could even be generating this error.
3. Even when I comment out the OS X deployment target in the podspec, so that it only builds for iOS and does not generate the OS X error, I still get "The podspec does not validate". No further reasons are presented. Why is this failing?

Without this podspec in the official directory, the usability of CocoaPods as a means of distributing Alamofire is greatly diminished. Please advise.

**Comment by segiddins** [comment]
@mattt you please please provide the verbose output for (3)?

**Comment by mattt** [comment]
```
** BUILD SUCCEEDED **

 -> Alamofire (1.1.3)

opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established
<- "POST /api/v1/pods HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nAuthorization: Token 186cf726f51820069f8c040dad7a6414\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nUser-Agent: Ruby\r\nHost: trunk.cocoapods.org\r\nContent-Length: 374\r\n\r\n"
<- "{\"name\":\"Alamofire\",\"version\":\"1.1.3\",\"license\":\"MIT\",\"summary\":\"Elegant HTTP Networking in Swift\",\"homepage\":\"https://github.com/Alamofire/Alamofire\",\"social_media_url\":\"http://twitter.com/mattt\",\"authors\":{\"Mattt Thompson\":\"m@mattt.me\"},\"source\":{\"git\":\"https://github.com/Alamofire/Alamofire.git\",\"tag\":\"1.1.3\"},\"platforms\":{\"ios\":\"8.0\"},\"source_files\":\"Source/*.swift\"}\n"
-> "HTTP/1.1 422 \r\n"
-> "Date: Fri, 09 Jan 2015 22:09:56 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 170\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin 1.6.2 codename Doc Brown\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 170 bytes...
-> "{\"error\":\"The Pod Specification did not pass validation.\",\"data\":{\"warnings\":[\"A value for `requires_arc` should be specified until the migration to a `true` default.\"]}}"
read 170 bytes
Conn keep-alive
[!] The Pod Specification did not pass validation.

/usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-trunk-0.5.0/lib/pod/command/trunk.rb:69:in `print_error'
/usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-trunk-0.5.0/lib/pod/command/trunk.rb:28:in `request_url'
/usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-trunk-0.5.0/lib/pod/command/trunk.rb:34:in `request_path'
/usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-trunk-0.5.0/lib/pod/command/trunk/push.rb:57:in `run'
/usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/claide-0.8.0/lib/claide/command.rb:312:in `run'
/usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-0.36.0.beta.1/lib/cocoapods/command.rb:45:in `run'
/usr/local/opt/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/cocoapods-0.36.0.beta.1/bin/pod:43:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.0.0-p353/bin/pod:23:in `load'
/usr/local/opt/rbenv/versions/2.0.0-p353/bin/pod:23:in `<main>'
```

**Comment by mattt** [comment]
The verbose output revealed the underlying issue: not having a `requires_arc` line. Why this doesn't show up in non-verbose output is probably worth investigating.

**Comment by mrackwitz** [comment]
>I don't know why the "Unable to load a specification for the plugin" warning is printing. Is this a known issue with this CocoaPods beta release?

This could be eventually related to the [RubyGems version](https://github.com/CocoaPods/CocoaPods/issues/2655#issuecomment-58890679) you're using. See CocoaPods/CocoaPods#2573. If I see it right, the causing / affected plugin (*cocoapods-try-release-fix*) is obsolete anyway and can be removed.

>(2) I cannot reproduce the OS X error when building for the OS X framework target using a deployment target of OS X 10.10. I'm not sure what part of that statement could even be generating this error.

I can reproduce this error, but I'm using another Xcode build (6A2008a), which ships:
```bash
$ xcrun swiftc -version
Swift version 1.1 (swift-600.0.56.1)
Target: x86_64-apple-darwin14.0.0
```
For some reason, the Swift compiler types `$1.value` as `() -> String?`, which would mean that it has to be called by `$1.value()` in this case, which clearly conflicts with the ad-hoc generated pseudo-Swift code, where `value` is defined as instance variable with a getter. If you would apply this change, it won't compile anymore for iOS, but for OS X only instead. I suppose that the standard dylibs differ in this point across the platforms, but the same swiftmodule is consolidated for the symbol definitions. I don't have validated yet if this still happens for the latest beta.

>(3) Even when I comment out the OS X deployment target in the podspec, so that it only builds for iOS and does not generate the OS X error, I still get "The podspec does not validate".

Thanks for figuring out the issue. :+1: The [cocoapods-core](CocoaPods/cocoapods-core) gem was outdated on trunk, which means that after the merge and deployment of CocoaPods/trunk.cocoapods.org#124, you could drop again the `requires_arc` statement from the specification as the migration then is completely fulfilled.

I saw that you was nonetheless able to publish the podspec, so I think this can be closed.
