### ISSUE TITLE
unable to create a pod while hiding the source code

### ISSUE THREAD

**Issue by leviyehonatan** [CocoaPods/swift#26]
is it at all possible to create such a project as in this link: https://github.com/leviyehonatan/cocoapods-lib-swift but not exposing the code to the user maybe by including somehow the .framework product as it is, but actually i do not know how to generate it, as it shows red in my xcode. this is a swift issue, because if i used objective-c i could have used a .a static lib, but this makes me use a dynamic embedded library.

**Comment by segiddins** [comment]
You are more than welcome to ship a binary dynamic framework as a pod. Tools such as https://github.com/CocoaPods/cocoapods-packager will also be updated to support frameworks in due time.

**Comment by leviyehonatan** [comment]
but how do i generate the dynamc framework file before cocoapods-packager supports it? and if i succeed doing so, is it supported by cocoapods to have a .framework only pod?

**Comment by leviyehonatan** [comment]
i have tried pod package anad these are the results :
Yehonatans-MacBook-Pro:cocoapods-lib-swift nickst$ pod package MySDK.podspec 
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Analyzing dependencies
Fetching podspec for `MySDK` from `MySDK.podspec`
Downloading dependencies
Installing MySDK (0.1.0)
Generating Pods project
Building framework
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: no files specified
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: no files specified
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: Pods/build/package.a (No such file or directory)
cp: Pods/MySDK/LICENSE: No such file or directory

**Comment by neonichu** [comment]
See CocoaPods/cocoapods-packager#56 for the issue tracking this. Also dynamic frameworks aren't fully supported as `vendored_frameworks` yet, see CocoaPods/CocoaPods#1993

**Comment by leviyehonatan** [comment]
so please just to make things perfectly clear, if i want to target pre 8.0 ios meaning 7.0 and i don't want to expose my code but i want to distribute it as a pod my ONLY way is to write in objective-c?

**Comment by neonichu** [comment]
The OS restriction is unrelated to it being a Pod or not, because Swift is only supported as a dynamic framework and those will be rejected by the App Store if you target iOS 7. Also keep in mind that Apple discourages distributing Swift frameworks anyway: <https://developer.apple.com/swift/blog/?id=2>.

**Comment by leviyehonatan** [comment]
so the answer is: yes? meaning 7.0 -> objective-c only?

**Comment by mrackwitz** [comment]
If your code should be distributed in binary form: yes, then the only option is as a static library, which implies (Objective-)C(++) only.
