### ISSUE TITLE
Static libraries not linked

### ISSUE THREAD

**Issue by cipriancaba** [CocoaPods/swift#28]
I am using `0.36.0.beta.1`

If I have a static library `libssl.a` in my spec, found at `TestSpec/Libs` and I include it as a vendored library, it doesn't seem to get linked in the target project

Here is my podspec file:

```Ruby
Pod::Spec.new do |s|
  s.name             = "TestSpec"
  s.version          = "0.0.1"
  s.summary          = "Test"
  s.homepage         = "https://www.google.com"
  s.author           = { "Ciprian Caba" => "1@2.com" }

  s.platform     = :ios, '8.0'
  s.requires_arc = true

  s.source           = { :git => "https://github.com/CocoaPods/CocoaPodsTest.git", :tag => s.version.to_s }

  s.source_files = 'TestSpec/*.{h,c,m,swift}'
  s.resource_bundles = {
    'TestSpecBundle' => ['TestSpec/*.png']
  }

  # s.public_header_files = 'Pod/Classes/**/*.h'
  s.frameworks = 'UIKit'
  s.vendored_libraries = 'TestSpec/Libs/libssl.a'
  s.libraries = 'ssl'
end
```

And here is my Podfile
```Ruby
platform :ios, '8.0'

target 'TestApp' do

pod 'TestSpec', :path => '../TestSpec'

end
```

What happens in the target project is that the libssl.a file gets included, the path to the Libs folder gets added to the Search path but on the Build Phases tab there is no linking done with the a file. From what I understood this should happen because of the `s.libraries = 'ssl'`

Please let me know if I am doing something wrong. I've also created a repo with a [test project](https://github.com/cipriancaba/cocoapods-static-lib)

**Comment by neonichu** [comment]
The purpose of the `libraries` attribute is linking libraries which are part of the platform SDK and in any case, they will always be linked using the generated XCConfigs, so they'll not be visible in the build phases tab, but in "Other Linker Flags".

**Comment by cipriancaba** [comment]
And is there any way to add them to the Build Phases tab directly from the podspec?

**Comment by neonichu** [comment]
Nope, most build settings are kept in XCConfigs deliberately.

**Comment by cipriancaba** [comment]
I understand now. Even if the lib is not added to the Build Phases tab, it's actually adding a linker flag `-l"ssl"` and this will actually build the library

![Linker flags](https://www.dropbox.com/s/gwc1dtq25yl899r/Screenshot%202015-01-21%2012.02.20.png?dl=1)

Thanks for clarifying this
