### ISSUE TITLE
Catch 22 base configuration warning

### ISSUE THREAD

**Issue by albertbori** [CocoaPods/swift#29]
I can't get [KIF](https://github.com/kif-framework/KIF) to work using cocoa pods 0.36.0.beta.2 (was able to reproduce also in 0.36.0.beta.1). Here is my Podfile:

	source 'https://github.com/CocoaPods/Specs.git'
	xcodeproj 'MyProject/MyProject.xcodeproj'
	link_with 'MyProject', 'UnitTests', 'AutomationTests'

	platform :ios, '8.0'

	pod 'MBProgressHUD', '~> 0.8'
	pod 'ActionSheetPicker-3.0'
	#Right here is where I reference a private swift framework cocoapod
	pod 'SDWebImage'
	pod 'Reachability'
	target 'AutomationTests', :exclusive => true do
	    pod 'KIF', '~> 3.0'
	end

When I run `pod install` I get the following warnings:

> [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `AutomationTests` to `../Pods/Target Support Files/Pods-AutomationTests/Pods-AutomationTests.debug.xcconfig` or include the `../Pods/Target Support Files/Pods-AutomationTests/Pods-AutomationTests.debug.xcconfig` in your build configuration.

> [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `AutomationTests` to `../Pods/Target Support Files/Pods-AutomationTests/Pods-AutomationTests.release.xcconfig` or include the `../Pods/Target Support Files/Pods-AutomationTests/Pods-AutomationTests.release.xcconfig` in your build configuration.

> [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `AutomationTests` to `../Pods/Target Support Files/Pods-AutomationTests/Pods-AutomationTests.qa.xcconfig` or include the `../Pods/Target Support Files/Pods-AutomationTests/Pods-AutomationTests.qa.xcconfig` in your build configuration.

Ignoring the warnings and attempting to build, I get the error:

> /Users/me/dev/MyProject/AutomationTests/AutomationTests-Bridging-Header.h:5:9: 'KIF/KIF.h' file not found

If I heed the warnings, and swap all the `AutomationTests` target's base configurations to `Pods-AutomationTests.[config].xcconfig`, and then attempt to build, I get the following error:

> /Users/me/dev/MyProject/AutomationTests/UI/MyTests.swift:9:8: Missing required modules: 'ActionSheetPicker_3_0', 'MBProgressHUD', 'MyPrivateSwiftPod', 'Reachability', 'SDWebImage'

The ironic thing, is that if I then run a `pod update`, it gives me the inverse warnings of the one above:

> [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `AutomationTests` to `../Pods/Target Support Files/Pods/Pods.debug.xcconfig` or include the `../Pods/Target Support Files/Pods/Pods.debug.xcconfig` in your build configuration.

> [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `AutomationTests` to `../Pods/Target Support Files/Pods/Pods.release.xcconfig` or include the `../Pods/Target Support Files/Pods/Pods.release.xcconfig` in your build configuration.

> [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `AutomationTests` to `../Pods/Target Support Files/Pods/Pods.qa.xcconfig` or include the `../Pods/Target Support Files/Pods/Pods.qa.xcconfig` in your build configuration.

I feel like CocoaPods might be a bit conflicted with respect to handling the special case that KIF requires in order to operate correctly. I also removed the `QA` build-config entirely to see if that would alleviate the warnings, but I still got the same warnings for `Debug` and `Release`.

Environment details:

- Yosemite Version 10.10.2 (14C109)
- Xcode Version 6.1.1 (6A2008a)

Related: In an attempt to find a work around where I could at least develop the tests while this gets sorted out, I ran into this issue: http://stackoverflow.com/questions/28227753/build-failed-no-such-module-kif/28228695

**Comment by kylef** [comment]
As mentioned in the contributing document for creating new issues, please attach sufficient steps to reproduce this issue or an example project exhibiting the problem.

> Ignoring the warnings and attempting to build, I get the error:
> /Users/me/dev/MyProject/AutomationTests/AutomationTests-Bridging-Header.h:5:9: 'KIF/KIF.h' file not found

This is because KIF is a framework in this case, you should instead reference it directly in your Swift files with `import KIF`.

**Comment by albertbori** [comment]
Unfortunately, that gives me almost the same error. On the `import KIF` line in the Swift file, it says:

> /Users/me/dev/MyProject/AutomationTests/UI/BioSettingsTests.swift:10:8: No such module 'KIF'

I will spend the next few hours assembling a sample project that highlights this issue.

**Comment by albertbori** [comment]
Added example project: https://github.com/albertbori/catch22

This fails in the exact same way as described above. All you have to do is add a Swift pod to your Podfile, run `pod install`, and it completely hoses KIF

**Comment by kylef** [comment]
@albertbori I've created a pull request on your example project fixing the problem https://github.com/albertbori/catch22/pull/1. This was a configuration issue in your Podfile, which won't be possible once https://github.com/CocoaPods/CocoaPods/issues/840 has been resolved.

**Comment by albertbori** [comment]
I was able to apply those concepts to my main project and it worked great!

Your help has been **invaluable**. Thank you so much!
