### ISSUE TITLE
Can't import Swift pods in playgrounds inside workspace

### ISSUE THREAD

**Issue by MrAlek** [CocoaPods/swift#3]
Just tried out the pre-release version of CocoaPods with Swift support and everything works great inside the main project. But when I add a playground to it, I can't get the import statements to work inside the playground (`No such module 'Moya'`). As I've understood it, this should work right out of the box, right?

Here's my podfile:
```ruby
platform :ios, '8.0'

pod 'Alamofire', :git => "https://github.com/mrackwitz/Alamofire.git", :branch => "podspec"
pod 'LlamaKit', :git => "https://github.com/AshFurrow/LlamaKit", :branch => "rac_podspec"
pod 'Moya', :git => "https://github.com/AshFurrow/Moya"
pod 'SwiftyJSON', :git => "https://github.com/SwiftyJSON/SwiftyJSON.git"
````

[Link to zip of the project](https://copy.com/kTJQkMkTD7ODSebp)

**Comment by EMidee66** [comment]
Is there a way to make Objective-C pods run in the playground ?
Swift pods are Ok, but with ObjC I keep getting an error.
![screen shot 2015-02-16 at 11 41 34 am](https://cloud.githubusercontent.com/assets/6751025/6210523/d6ac0e48-b5d0-11e4-86e8-a7455770c7ca.png)

**Comment by neonichu** [comment]
@EMidee66 ObjC Pods generally work fine in Playgrounds, they need to be build for 64-bit if used in an iOS one, though.

**Comment by neonichu** [comment]
Underlying problem is tracked by CocoaPods/CocoaPods#3095

**Comment by dcflow** [comment]
Thank you Boris.

**Comment by joelparkerhenderson** [comment]
@neonichu @mrackwitz Is there progress on your idea of putting the pods in a playground-accessible directory? 

My goal is to create a playground, then do "import Alamofire" in the playground. I'm building with Xcode 6.4, and using Cocoapods 0.36.4. I'm reading lots of docs, but I haven't found one that tells step-by-step how to get this working. Advice is much appreciated. Thanks!

**Comment by neonichu** [comment]
Nothing has happened towards this so far, but you can symlink the frameworks from Pods-\* to the root of `${BUILD_PRODUCTS_DIR}` - you could also try to experiment with the stuff in https://github.com/neonichu/quick-cli-runner/pull/3 to make Playgrounds work with custom framework search paths.

**Comment by joelparkerhenderson** [comment]
Thanks. Can you say more about your suggestion?

I don't see any BUILD_PRODUCTS_DIR.

I do see a BUILT_PRODUCTS_DIR, found this way:

```
$ xcodebuild -project MyProject.xcodeproj -target "MyTarget" -showBuildSettings | grep "\bBUILT_PRODUCTS_DIR\b"
BUILT_PRODUCTS_DIR = /Users/me/Library/Developer/Xcode/DerivedData/MyProject-ejqijzrqxgnsqqkhufjmtoxlyhztg/Build/Products/Release-iphoneos
```

But that directory doesn't exist. 

I see a similar directory:

```
/Users/me/Library/Developer/Xcode/DerivedData/MyProject-gchobkltsdgbkkdzrnmrwuoqsanws/Build/Products/Debug-iphonesimulator
```

Within that directory, I see:

```
Pods/Alamofire.framework
```

Is that the framework that you're suggesting to symlink?

```
ln -lsf \
  /Users/me/Library/Developer/Xcode/DerivedData/MyProject-gchobkltsdgbkkdzrnmrwuoqsanws/Build/Products/Debug-iphonesimulator/Pods/Alamofire.framework \
  /Users/me/Library/Developer/Xcode/DerivedData/MyProject-ejqijzrqxgnsqqkhufjmtoxlyhztg/Build/Products/Release-iphoneos/
```

**Comment by neonichu** [comment]
Yah, sorry, that is what I meant.

I'm not 100% positive which platform Playgrounds use, but I'd think it is `Debug-iphonesimulator`, so you would have to create the link in that directory. They run on your Mac, so it is definitely not `iphoneos`
