### ISSUE TITLE
pod install doesn't create a bridging header

### ISSUE THREAD

**Issue by getaaron** [CocoaPods/swift#30]
**Summary**: `pod install` doesn't create a bridging header

**Reproduction Steps**

1. Create a new project in Xcode
2. Run `pod install`
3. Add some pods into the empty `Podfile`, for example:

    ```bash
# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'Example' do

pod 'FXForms'
pod 'UICountingLabel'

end

target 'ExampleTests' do

end
    ```
4. Run `pod install` again to install the pods
5. Close the project and open the `.xcworkspace` in Xcode

**Expected Behavior**

I expect that I can now use my imported pods in a `.swift` file.

**Actual Behavior**

I cannot use the pods until I manually create a bridging header.

**Notes**

Using CocoaPods 0.36.0.beta.2 and Xcode Version 6.2 (6C121)

**Comment by getaaron** [comment]
(If this is expected behavior, then it would great for the output of `pod install` / `pod update` to mention this.)

**Comment by segiddins** [comment]
That is the expected behavior unless you use the `use_frameworks!` flag for a target.

**Comment by getaaron** [comment]
Thanks for the clarification. Just as CocoaPods informs users:

    [1] From now on use `Example.xcworkspace`.

it should also inform users to manually create a bridging header.

**Comment by segiddins** [comment]
Framework support is still in beta, and you don't need to create a bridging header when using Objective-C.

**Comment by corinnekrych** [comment]
Similar to @getaaron I have a project using a dependency in its podfile without `use_frameworks!` 
 => you have to define bridging hear. 
See https://github.com/corinnekrych/aerogear-ios-http-1/blob/using.OHHTTPStubs/AeroGearHttp.xcodeproj%2Fproject.pbxproj#L540
Podfile: https://github.com/corinnekrych/aerogear-ios-http-1/blob/using.OHHTTPStubs/Podfile

But here another project where although not using `use_frameworks!` I get a fwk behavior 
=> ie: no bridging header needed
See https://github.com/corinnekrych/aerogear-ios-oauth2-1/blob/using.OHHTTPStubs/AeroGearOAuth2.xcodeproj/project.pbxproj#L617
Podfile: 
https://github.com/corinnekrych/aerogear-ios-oauth2-1/blob/using.OHHTTPStubs/Podfile

@segiddins why is there 2 different behaviors? there is something i don't understand....

**Comment by mrackwitz** [comment]
@corinnekrych: CocoaPods 0.35 built static libraries exclusively and didn't had support for Clang modules. With `use_frameworks!` you integrate your dependencies as frameworks. Frameworks bring Clang modules under the hood by carrying a module.modulemap, where Clang is advised where it can find the headers which belong to this specific dependency, which allows them to be imported by e.g. `@import AFNetworking;`.

**Comment by segiddins** [comment]
@corinnekrych in master now, you'll need to specify `use_frameworks!` all the time, instead of it being inferred when there are swift pods in the target.

**Comment by corinnekrych** [comment]
ah oki I understand now... the difference between my 2 projects is that ios-http does not use any swift pod whereas ios-oauth2 do use a swift pod 
=> hence `use_frameworks!` was inferred 

I guess having to write it explicitly makes more sense. Thanks!

For information: https://github.com/CocoaPods/CocoaPods/commit/681eb76a328717312d17ce23f4bab428bab7f8ce
