### ISSUE TITLE
Can't get image from xcasset

### ISSUE THREAD

**Issue by albertbori** [CocoaPods/swift#31]
I'm not sure if this is caused by Swift/Frameworks support, but I am using `0.36.0.beta.2`. I have a pod that tries/fails to load images from the current bundle like so:

    let bundle = NSBundle(forClass: MyBundleClass.self)
    if let image = UIImage(named: "Add", inBundle: bundle, compatibleWithTraitCollection: nil) {
        self.frame.size = image.size
        self.setImage(image, forState: UIControlState.Normal)
    } else {
        NSLog("%@", "Failed to find \"Add\" image in bundle: \(bundle.bundleIdentifier) \(bundle.bundlePath)")
    }

Which results in no image loaded, and the following log:

> Failed to find "Add" image in bundle: Optional("org.cocoapods.MyPod") /Users/me/Library/Developer/CoreSimulator/Devices/29008343-5A97-47FB-B0E6-66D18A331BDA/data/Containers/Bundle/Application/7251591F-F19F-4914-819C-DB64BABA25A7/MyApp.app/Frameworks/MyPod.framework

MyPod.podspec:

    Pod::Spec.new do |s|
      s.name             = "MyPod"
      s.version          = "0.1.13"
      s.summary          = "MyPod"      
      s.homepage         = "https://github.com/MyCompany/MyPod"
      s.author           = { "Me" => "me@gmail.com" }
      s.source           = { :git => "https://github.com/MyCompany/MyPod.git", :tag => s.version.to_s }

      s.platform     = :ios, '8.0'
      s.requires_arc = true

      s.source_files = 'Pod/Classes'
      s.resource_bundles = {
        'MyPod' => ['Pod/Assets/*.png', 'Pod/Assets/*.xib', 'Pod/Assets/*.xcassets']
      }

       s.public_header_files = 'Pod/Classes/**/*.h'
       s.module_name = 'MyPod'
    end

In my main project, I include the pod like so:

    pod 'MyPod', :git => "https://github.com/MyCompany/MyPod", :tag => "0.1.13"

The asset file in question is: `Pod/Assets/Images.xcassets`, which CocoaPods seems to find just find to include in the Pods project:

![screen shot 2015-02-11 at 4 07 33 pm](https://cloud.githubusercontent.com/assets/1742709/6158501/29d02842-b208-11e4-845a-d89d4e96b6ac.png)

Thoughts?

**Comment by segiddins** [comment]
that's because you're specifying a custom resource bundle, instead of using the framework bundle.

**Comment by albertbori** [comment]
I'm not sure I follow. What would you change in the above code snippets to correct this?

**Comment by segiddins** [comment]
Try changing

```ruby
s.resource_bundles = {
    'MyPod' => ['Pod/Assets/*.png', 'Pod/Assets/*.xib', 'Pod/Assets/*.xcassets']
  }
```

to 

```ruby
s.resources = ['Pod/Assets/*.png', 'Pod/Assets/*.xib', 'Pod/Assets/*.xcassets']
```

?

**Comment by neonichu** [comment]
@segiddins Looks right.

Alternatively, one could also get the inner bundle using something like:

```
var bundle = NSBundle(forClass: MyBundleClass.self)
bundle = NSBundle(URL: bundle.URLForResource("MyPod", withExtension: "bundle")!)!
```

**Comment by albertbori** [comment]
You guys are 100% right. Thanks for steering me in the right direction. Hopefully, this issue will serve as google food for future travelers.

One last question for extra credit: The following image name reference in a xib:

![screen shot 2015-02-11 at 5 13 17 pm](https://cloud.githubusercontent.com/assets/1742709/6159342/60998bbc-b211-11e4-9c6b-c39c254a8645.png)

Fails with:

> Could not load the "Email-Small" image referenced from a nib in the bundle with identifier "(null)"

How would you correct this, using the default bundle that @segiddins mentioned?
