### ISSUE TITLE
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.3'

### ISSUE THREAD

**Issue by thalescm** [CocoaPods/swift#33]
I'm developing a swift app in iOS.  
In my app I'll use GoogleMaps API, which in it's current version can only be added via Pods.

That said, I've configured my DevelopmentTeam to my account. Chosen the correct provisioning profile and Code Signing Identity.

It runs normally in simulator, but when trying to build and run in a physical device it fails with the below error:  
`CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.3'`

My deployment target in both app and Pods project is set to 8.0  
I've tried to add a development Team in Pods project, add the provisioning and signing identifier, and even changed the Pods bundle identifier to be the same of the app with `.Pods-appname` (the unchangeable part) at the end (example `com.mycompany.appname.Pods-appname`). The same error persists.

Any one have an idea on how to solve this?

**Comment by segiddins** [comment]
This should be fixed on master.
