### ISSUE TITLE
Can't seem to locate images inside "Resources" folder of Embedded Framework dependency 

### ISSUE THREAD

**Issue by samjarman** [CocoaPods/swift#35]
The SDK I'm working with is a .embeddedframework which has a resource bundle for images/nibs and .framework for the code.

The SDK loads images like:    `UIImage *image = [UIImage imageNamed:[NSString stringWithFormat:@"<Product>Resources.bundle/%@", name]];`

When I use it with Cocoapods and Swift, with `use_frameworks!` in the podfile, the SDK fails to find these images at runtime. 

Question: How should an Obj-C author safely load up images from their own embedded framework's resource bundle to show in both ObjC and Swift 1.X and 2.X apps?

**Comment by segiddins** [comment]
you'll have to use the APIs that allow you to specify a bundle, and use `[NSBundle bundleForClass:]`

**Comment by samjarman** [comment]
I'm still having issues, I've tried the approaches from here: http://www.the-nerd.be/2015/08/07/load-assets-from-bundle-resources-in-cocoapods/ and here: http://blog.flaviocaetano.com/post/cocoapods-and-resource_bundles/ with no luck. Any more advice @segiddins?

More info: 

I have `s.resource_bundles = {'NAMEResources' => 'NAME.embeddedframework/NAME.framework/Versions/A/Resources/NAMEResources.bundle'}` in my pod spec, so it's making a file called 
NAMEResources.bundle

The directory structure looks like 

MySwiftApp.app > Frameworks > NAME.framework > NAMEResources.bundle > thefileiwant.png 

The SDK is called from swift code, but the SDK itself is objective C.

Been experimenting with some code

```
+ (UIImage *)xyz_imageNamed:(NSString *)name {
    Class NAME = (Class _Nonnull)NSClassFromString(@"NAME");
    NSBundle *NAMEBundle = [NSBundle bundleForClass:NAME];
    NSURL *bundleURL = [[NSBundle bundleForClass:self.classForCoder]  URLForResource:@"NAMEResources" withExtension:@"bundle"];

    if (bundleURL) {
        NSBundle *actualBundle = [[NSBundle alloc] initWithURL:bundleURL];
        NSLog(@"actualBundle = %@", actualBundle);
    }

    UIImage *image = [UIImage imageNamed:[NSString stringWithFormat:@"NAMEResources.bundle/%@",name]];
    UIImage *image2 = [UIImage imageNamed:name inBundle:NAMEBundle compatibleWithTraitCollection:nil];
    UIImage *image3 = [UIImage imageNamed:[NSString stringWithFormat:@"NAMEResources.bundle/%@",name] inBundle:NAMEBundle compatibleWithTraitCollection:nil];

    NSString *bundlePath = [[NSBundle mainBundle] pathForResource:@"NAMEResources" ofType:@"bundle"];

    NSBundle *bundle = [NSBundle bundleWithPath:bundlePath];

    UIImage *image4 = [UIImage imageNamed:name inBundle:bundle compatibleWithTraitCollection:nil];


    NSLog(@"IMAGE 1 = %@", image);
    NSLog(@"IMAGE 2 = %@", image2);
    NSLog(@"IMAGE 3 = %@", image3);
    NSLog(@"IMAGE 4 = %@", image4);

    NSLog(@"NAME class = %@", NAME);
    NSLog(@"NAMEBundle = %@", NAMEBundle);
    NSLog(@"bundleURL = %@", bundleURL);
    NSLog(@"All Bundles = %@", [NSBundle allBundles]);

    if (!image) {
        image = [UIImage imageNamed:name];
    }

    return image;
}
```

all the `imageX` variables are nil, `NAME`is non-nill, `NAMEBundle` is non-nil but `bundleURL` is also nil

Quite stuck. Would like swift users of the SDK to be able to see the images used by the SDK.

**Comment by samjarman** [comment]
I should mention this is for development pods too... the structure comes out real weird. 

Development Pods > Frameworks | Resources 

Resources/Name.embeddedframework/name.framework/Versions/A/Resources/NAMEResources.bundle/fileiwant.png

**Comment by segiddins** [comment]
I can't come up with anything off the top of my head, sorry.
