### ISSUE TITLE
Could not build Objective-C module 'IIOCUtilities'

### ISSUE THREAD

**Issue by hatjs880328s** [CocoaPods/swift#36]
Hi,
 
I create a lib with obj-c it's pod address is "https://github.com/hatjs880328s/IIOCUtilities"

I wanna create a pod lib with swift , but it's alert is "Could not build Objective-C module 'IIOCUtilities'"

how can i solve it ?

I will be deeply appreciated that you have done for me and look forward to your reply.

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
