### ISSUE TITLE
UrbanAirship-iOS-SDK not working as framework due to sqlite3.h

### ISSUE THREAD

**Issue by fluidsonic** [CocoaPods/swift#8]
I added `UrbanAirship-iOS-SDK` to the project as a framework pod.
But since the library's public headers import `sqlite3.h` which is not a module and thus Xcode rejects the import as invalid.

### Code
```
import UrbanAirship_iOS_SDK
```

### Error
```
Pods/UrbanAirship-iOS-SDK/Airship/Common/UASQLite.h:28:9: Include of non-modular header inside framework module 'UrbanAirship_iOS_SDK.UASQLite'
```
at:
```
#import "sqlite3.h"
```

## Bridging

Using the bridging header also doesn't work since headers of framework pods are not added to the search path.

### Code
```
#import <UrbanAirship-iOS-SDK/AirshipLib.h>
```
### Error
```
Bridging.h:16:9: 'UrbanAirship-iOS-SDK/AirshipLib.h' file not found
```

The file exists though:
```
$ ls Pods/Headers/Public/UrbanAirship-iOS-SDK/AirshipLib.h 
Pods/Headers/Public/UrbanAirship-iOS-SDK/AirshipLib.
```

## Ideas for Solution
I see four possible solutions here:

1. Allow setting `use_frameworks` on a per-pod basis (requires bridging). Doesn't solve the actual issue though and won't work for framework targets.
2. Add framework headers to the header search path (requires bridging). Doesn't solve the actual issue though and won't work for framework targets.
3. Let CocoaPods automatically create modules for sqlite3 and other common non-modular libraries when they're set as dependencies using `libraries`.
4. Provide instructions to users on how they can make a module out of libraries required by pods on their own.

I'd prefer `#3` if possible.

**Comment by neonichu** [comment]
Users can bring their own module maps with a specification by configuring `SWIFT_INCLUDE_PATHS` via the `xcconfig` attribute. So there is no need for CP changes to support this.
