### ISSUE TITLE
Dynamic Framework Support with iOS 7 (Swift or otherwise)

### ISSUE THREAD

**Issue by bssayeda** [CocoaPods/swift#9]
I have been keeping an eye on the swift support coming in Cocoapods 0.36 and one thing I noticed is that only iOS 8+ will get support for Pods being linked as Dynamic frameworks.  Is there a reason for this?  Swift is supported on iOS 7 and when you have a project that uses swift Xcode automatically includes some portions of the Swift Runtime in the project in the form of dynamic frameworks.  Also, if you create a new project that targets iOS 7 that includes a Dynamic Framework the Application does build fine and will link to the Dynamic Framework on iOS 7 devices.  I can push up a test project that demonstrates this if needed.

**Comment by cemolcay** [comment]
hi all, just to be clear, can we use objective-c pods in swift projects targeting ios 7 ? 
is that legal ?

**Comment by neonichu** [comment]
Yes, but you have to integrate them as static libraries (which is still the default) and use a bridging header.

**Comment by alfiehanssen** [comment]
@neonichu What if you want to include the Objective-C Cocoapod in a Swift framework target that needs to support iOS7+? Framework targets cannot include bridging headers. Any ideas?
